apiVersion: v1
items:
  - apiVersion: v1
    data:
      .dockerconfigjson: $CHANGE_SECRET
    kind: Secret
    metadata:
      name: regcred-docker
      namespace: fastpyfolio
    type: kubernetes.io/dockerconfigjson

  - apiVersion: v1
    kind: ConfigMap
    metadata:
      name: fastpyfolio-config
      namespace: fastpyfolio
    data:
      DB_URL: fastpyfolio-mongodb:27017
      DB_USER: fastpyfolio
      DB_PASSWORD: $CHANGE_SECRET

  - apiVersion: v1
    kind: Secret
    metadata:
      name: mongodb-secret
      namespace: fastpyfolio
    type: Opaque
    data:
      MONGO_ROOT_USERNAME: $CHANGE_SECRET
      MONGO_ROOT_PASSWORD: $CHANGE_SECRET
      MONGO_USERNAME: $CHANGE_SECRET
      MONGO_PASSWORD: $CHANGE_SECRET
      MONGO_USERS_LIST: $CHANGE_SECRET

kind: List
metadata:
  resourceVersion: ""
