apiVersion: v1
items:
  # --- API BACKEND ---

  - apiVersion: v1
    kind: Service
    metadata:
      labels:
        app: fastpyfolio-api
      name: fastpyfolio-api
      namespace: fastpyfolio
    spec:
      ports:
        - nodePort: 31701
          port: 8001
          protocol: TCP
          targetPort: 8001
      selector:
        app: fastpyfolio-api
      type: NodePort

  # --- WWW FRONTEND ---

  - apiVersion: v1
    kind: Service
    metadata:
      labels:
        app: fastpyfolio-www
      name: fastpyfolio-www
      namespace: fastpyfolio
    spec:
      ports:
        - nodePort: 31700
          port: 8000
          protocol: TCP
          targetPort: 8000
      selector:
        app: fastpyfolio-www
      type: NodePort

  # --- MONGO DB ---

  - apiVersion: v1
    kind: Service
    metadata:
      namespace: fastpyfolio
      name: fastpyfolio-mongodb
      labels:
        app: fastpyfolio-mongodb-svc
    spec:
      type: NodePort
      selector:
        app: fastpyfolio-mongodb

      ports:
        - port: 27017
          targetPort: 27017
          nodePort: 31702

kind: List
metadata:
  resourceVersion: ""
